//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvdeEczane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adresler()
        {
            this.Siparisler = new HashSet<Siparisler>();
        }
    
        public int ID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string AdresAdi { get; set; }
        public string AdresAciklama { get; set; }
        public string AdresUlke { get; set; }
        public string AdresSehir { get; set; }
        public string AdresIlce { get; set; }
        public string AdresTel { get; set; }
        public string AdresCepTel { get; set; }
        public string AdresTc { get; set; }
        public string FaturaTip { get; set; }
        public string KargoAdi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparisler { get; set; }
    }
}
