//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvdeEczane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilgiler
    {
        public int ID { get; set; }
        public string SiteLogo { get; set; }
        public string SiteTel { get; set; }
        public string FirmaAdi { get; set; }
        public string SiteEmail { get; set; }
        public string SiteInstagram { get; set; }
        public string SiteHakkimizda { get; set; }
        public string LogoAdi { get; set; }
    }
}
