//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvdeEczane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bloglar
    {
        public int ID { get; set; }
        public string BlogAdi { get; set; }
        public string BlogAciklama { get; set; }
        public Nullable<System.DateTime> BlogTarih { get; set; }
        public string BlogResim { get; set; }
        public string BlogKisaAciklama { get; set; }
    }
}
