//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvdeEczane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kampanyalar
    {
        public int ID { get; set; }
        public string KampanyaAdi { get; set; }
        public string KampanyaAciklama { get; set; }
        public string KampanyaURL { get; set; }
        public string KampanyaResim { get; set; }
    }
}
