//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvdeEczane.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EVDEECZANEEntities3 : DbContext
    {
        public EVDEECZANEEntities3()
            : base("name=EVDEECZANEEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Adresler> Adresler { get; set; }
        public virtual DbSet<Bilgiler> Bilgiler { get; set; }
        public virtual DbSet<Bloglar> Bloglar { get; set; }
        public virtual DbSet<Kampanyalar> Kampanyalar { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Marka> Marka { get; set; }
        public virtual DbSet<Menuler> Menuler { get; set; }
        public virtual DbSet<SEO> SEO { get; set; }
        public virtual DbSet<SiparisDetay> SiparisDetay { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<Stok> Stok { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
    }
}
