//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvdeEczane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stok()
        {
            this.SiparisDetay = new HashSet<SiparisDetay>();
            this.Yorumlar = new HashSet<Yorumlar>();
        }
    
        public int ID { get; set; }
        public string StokAdi { get; set; }
        public string StokResim { get; set; }
        public string StokResimAdi { get; set; }
        public Nullable<int> StokMarkaID { get; set; }
        public Nullable<int> StokKategoriID { get; set; }
        public Nullable<int> StokYorumID { get; set; }
        public string StokKodu { get; set; }
        public string StokBarkod { get; set; }
        public Nullable<decimal> StokFiyat { get; set; }
        public Nullable<int> StokBakiye { get; set; }
        public Nullable<System.DateTime> StokTarih { get; set; }
        public string StokAciklama { get; set; }
        public Nullable<bool> isTrend { get; set; }
        public Nullable<bool> isYeni { get; set; }
        public Nullable<bool> isIndirim { get; set; }
        public Nullable<decimal> IndirimliFiyat { get; set; }
        public Nullable<int> ParentKategoriID { get; set; }
        public Nullable<int> AnaKategoriID { get; set; }
    
        public virtual Marka Marka { get; set; }
        public virtual Menuler Menuler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
    }
}
